messages:
  start: "Привет, давай знакомиться!
\nЯ чат-бот ГК Smart. Помогу оперативно найти ответ на твой вопрос, нужный документ или регламент, а также подскажу контакты коллег!
\nЧтобы я дал корректный ответ на твой вопрос, прошу тебя задавать мне максимально понятный и подробный вопрос!"

keyboard:
  add_profile: "Меню"
  edit_profile: "..."
