messages:
  start: "Привет, давай знакомиться!
\n\nЯ чат-бот ГК Smart. Помогу оперативно найти ответ на твой вопрос, нужный документ или регламент, а также подскажу контакты коллег!
\nЧтобы я дал корректный ответ на твой вопрос, прошу тебя задавать мне максимально понятный и подробный вопрос!
\n\n1. Пример вопроса, на который я смогу найти ответ: \"Расскажи о действиях, которые необходимо сделать самозанятому после получения выплаты\"
\n2. Пример вопроса, на который я не смогу найти ответ, либо он будет некорректным: \"Расскажи про выплаты\"
"


keyboard:
  add_profile: "Меню"
  edit_profile: "..."
